import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={` antialiased bg-white${roboto.className} bg-white`}>
        <Navbar></Navbar>
        <div className="md:px-20 mx-auto"> {children}</div>

        <Footer></Footer>
      </body>
    </html>
  );
}
